### PR TITLE
password strength meter style added to storefront ref #245

### PR DESCRIPTION
**Pull request by nishitlangaliya**
new password strength meter style added for storefront theme

### CODE REVIEW

**Comment by nishitlangaliya** [comment]
any update?

**Comment by jameskoster** [comment]
Sorry, been travelling. Commented here (which affects this PR): https://github.com/woothemes/woocommerce/pull/9319#issuecomment-147782904

**Comment by claudiosmweb** [comment]
Done, just change to `.woocommerce-password-strength`.

**Comment by jameskoster** [comment]
@nishitlangaliya The colors should match the Storefront colors used for WooCommerce messages.

**Comment by nishitlangaliya** [comment]
@jameskoster Thanks for the reply. Will  change the colors match to storfront theme  asap . And will do PR for the same.

Please let me know thougths for the same.

**Pull request merged**
