### PR TITLE
Add missing hooked function

### PR DESCRIPTION
**Pull request by WPprodigy**
Should these have the same priority?

https://github.com/woothemes/storefront/blob/master/inc/structure/hooks.php#L76

### CODE REVIEW

**Comment by jameskoster** [comment]
@WPprodigy No, comments should have priority 20. Wanna update your PR? :-P

**Comment by WPprodigy** [comment]
Oh? How come? They both show priority 10 here: https://github.com/woothemes/storefront/blob/master/inc/structure/hooks.php#L75-L76

I would think comments should be moved up to 20 though?

**Comment by jameskoster** [comment]
> How come?

Because if they both have the same priority nothing can be added between them.

Think this was just an oversight when this code was originally written.

**Comment by WPprodigy** [comment]
Oops, sorry about that earlier comment. I misread your post and thought you were saying that just the commented line should say 20 ;p

Thought I deleted it in time though, so now there is just an awkward gap in conversation

**Comment by jameskoster** [comment]
Too much Mt. Dew.

Thanks man xD

**Pull request merged**
