### PR TITLE
Included notice for Theme Customisations

### LINKED ISSUE #361: Add a notice on theme-editor.php to install the theme customisations plugin
As discussed here: https://github.com/woothemes/storefront/pull/360

- [x] Upload [theme-customisations](https://github.com/woothemes/theme-customisations) plugin to .org
- [ ] Add notice with inline installer on `theme-editor.php`.

### PR DESCRIPTION
**Pull request by BurlesonBrad**
closes #361

### CODE REVIEW

**Comment by jameskoster** [comment]
> As INCREDIBLE as Storefront is, you might want to customize your Storefront to fit your own needs

Not sure we should be blowing our own trumpet quite so hard :p 

> Should you need to customize Storefront, we recommend...

Think we can lose the UTM codes as well :')

**Comment by BurlesonBrad** [comment]
.......fine :wink: 
UTM gone. :+1: 
Blowing own :trumpet: stays.

**Comment by jameskoster** [comment]
Haha, the trumpet has to go man, sorry :p

**Comment by BurlesonBrad** [comment]
cleaned up and ready to be merged

**Comment by jameskoster** [comment]
Gracias amigo!

**Pull request merged**
