### PR TITLE
Check for featured products on 404 page

### PR DESCRIPTION
**Pull request by WPprodigy**
Prevent this: http://cld.wthms.co/1aptw/1UlXRHz6

By turning it into this: http://cld.wthms.co/SIJz/1DstbzTT

Could also do a check to see if products are on sale and show that before reverting to recently added.

### CODE REVIEW

**Comment by WPprodigy** [comment]
On second glance, could also make a storefront function that checks behind the scenes for featured products, then sale products. If one of them is found, then the function would output the correct shortcode. If no featured or sale products are found, then it would revert to recently added.

This could help clean up the code/logic needed in the template. Just a thought :)

**Comment by jameskoster** [comment]
> On second glance, could also make a storefront function that checks behind the scenes for featured products, then sale products. If one of them is found, then the function would output the correct shortcode. If no featured or sale products are found, then it would revert to recently added.

Nice idea. You wanna work on this @WPprodigy or happy for me to take over?

**Comment by WPprodigy** [comment]
I can give it a go:)

**Comment by jameskoster** [comment]
Any idea when you plan to do this @WPprodigy ? Would like to get a release out this week.

**Comment by WPprodigy** [comment]
How's that? Tried to make it so the function can be extended and used elsewhere.

**Comment by jameskoster** [comment]
Looks good @WPprodigy. Couple of tiny last points;

* I reckon we can make the function name a little nicer, something like `storefront_promoted_products()`?.
* Maybe add a `$recent` arg, so there's an option to disable the recent products fall back?
* 'Products On Sale' can just be 'On Sale Now'
* 'Recently Added Products' can be 'New In Store'.

**Comment by WPprodigy** [comment]
I agree on the function name. Was struggling to name it haha xD

**Comment by jameskoster** [comment]
Perfection! Thanks once again :-)

**Pull request merged**
